version: '3.4'
services:
  web:
    restart: unless-stopped
    build: .
    environment:
      TZ: "America/New_York"
    env_file:
      - .env
    expose:
      - "80"
    ports:
      - "5000:80"
    volumes:
      - ./app/:/app